### ISSUE TITLE
How on earth do I install it?

### ISSUE THREAD

**Issue by fengchangfight** [solo-io/squash#121]
I didn't see nothing on the official site doc, there's a installation link , but nothing about installation...

**Comment by rettori** [comment]
Hi Feng, 
check our docs on how to install and get started. https://squash.solo.io/overview/

**Comment by fengchangfight** [comment]
> Hi Feng,
> check our docs on how to install and get started. https://squash.solo.io/overview/

thank you ,  did you just update the page, last time I went there it's 404...
