### ISSUE TITLE
0.5.1 docker image can not pull from docker hub.

### ISSUE THREAD

**Issue by hgword** [solo-io/squash#130]
https://hub.docker.com/r/soloio/squash/tags

that docker image only has DEV tag.
![image](https://user-images.githubusercontent.com/1271836/54095951-0fa08900-43ed-11e9-83a0-853b507381f9.png)

so I failed to run squash 0.5.1 version.
please check it.

**Comment by sanha** [comment]
![image](https://user-images.githubusercontent.com/8844176/54096020-57271500-43ed-11e9-9887-ae1e20dd5489.png)
Same here. The squash pod in `squash-debugger` namespace fails because of "ErrImagePull".

**Comment by mitchdraft** [comment]
https://github.com/solo-io/squash/pull/131

also configurable now via:
https://github.com/solo-io/squash/pull/133

thank you!

**Comment by sanha** [comment]
The image cannot be loaded for release 0.5.2 again.
It seems that the path of the docker image is still broken.

When I deploy execute following command with squashctl version 0.5.2, 
```bash
squashctl deploy squash
kubectl edit deployment -n squash-debugger
```
the image path in the deploy config was `image: quay.io/solo-io/0.5.2:0.5.2`.
In my thought, it should be `image: quay.io/solo-io/squash:0.5.2`.

Please take a look!
