### ISSUE TITLE
0.5.2 docker image can not be pulled

### ISSUE THREAD

**Issue by sanha** [solo-io/squash#136]
A similar problem that caused #130 recurs.
The 0.5.2 squash docker image cannot be loaded.
It seems that the path of the docker image is still broken.

When I deploy execute following command with squashctl version 0.5.2, 
```bash
squashctl deploy squash
kubectl edit deployment -n squash-debugger
```
the image path in the deploy config was `image: quay.io/solo-io/0.5.2:0.5.2`.
In my thought, it should be `image: quay.io/solo-io/squash:0.5.2`.

Please take a look!

**Comment by mitchdraft** [comment]
thanks for catching this @sanha , sorry about that!

**Comment by mitchdraft** [comment]
fixed with https://github.com/solo-io/squash/releases/tag/v0.5.3
thank you for reporting this!
