### ISSUE TITLE
update solo-kit, do not register CRD's on client creation

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/squash#155]
The latest solo-kit lets you create clients without having to register the CRDs
This allows us to implement our secure-mode design, where users should not need permission to register CRDs.

**Comment by mitchdraft** [comment]
@sanha this addresses the permissions issue you flagged on slack

**Comment by hgword** [comment]
👍

**Comment by hgword** [comment]
@mitchdraft 
helloo mkitchdraft
do u have any plan or schedule to fix this issue? we are waiting for fix this issue :-)

**Comment by mitchdraft** [comment]
Thanks for bumping this, I didn't realize it was blocking you @hgword 
work in progress here: https://github.com/solo-io/squash/pull/166
please review the permissions given to the service accounts and let me know if this will meet your needs:
plank: https://github.com/solo-io/squash/pull/166/files#diff-3135f81fd585ae03a9477219dc9e3b4eR251
squash: https://github.com/solo-io/squash/pull/166/files#diff-f7ed3785f15d52d757d380b0d1dd6e87R72
I should be able to merge this update this week

fyi, the key change was: https://github.com/solo-io/squash/pull/166/files#diff-b734217cbcb93350b77bfd9e1f40f668R30 - that allows us to get a resource client without registering the crd along the way. This is possible since we updated solo-kit

**Comment by mitchdraft** [comment]
@sanha @hgword this feature has been implemented
Now, when using secure-mode, squash will not try to register the DebugAttachment CRD
It will assume that you (or an admin with CRD registration permissions) had already registered it with `squashctl utils register-resources`

Let me know if this works for you or if you want registration to be disabled in non-secure mode as well

**Comment by orlando-jamie** [comment]
Hi @mitchdraft. Which version was this fixed in? I tried removing the permissions to create CRDs from both squash and plank to support secure mode. However, when I go to run squashctl, it looks like the squash and plank containers both try to register the CRDs anyway still.

```json
failed to register crd: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:squash-debugger:squash-plank" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
{"level":"fatal","ts":1569351347.7799358,"caller":"plank/main.go:27","msg":"debug failed!","error":"failed to register crd: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:squash-debugger:squash-plank\" cannot create resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope","stacktrace":"main.main\n\t/Users/mitch/go/src/github.com/solo-io/squash/cmd/plank/main.go:27\nruntime.main\n\t/usr/local/Cellar/go/1.11.1/libexec/src/runtime/proc.go:201"}
```
