### ISSUE TITLE
delete-planks has to be filtered

### ISSUE THREAD

**Issue by dwojciec** [solo-io/squash#162]
I'm using an openshift  multi user env on which each developer has his own infrastructure application project and we decided to use it to deploy plank when we are debugging. 
Example : project called "infra22" on which we have multiple application (pod) running but by executing 
```
 squashctl utils delete-planks --squash-namespace infra22
```
the result is 
```
delete-planks --squash-namespace infra22
Found 4 plank pods in namespace infra22
Deleted plank pod kiali-7df9d879b4-dqvvg.
Deleted plank pod plank2mbjl.
Deleted plank pod plankc7kmt.
Deleted plank pod plankpjxxr.
```
the delete is removing all PODS !!!  in my case the kiali pod is deleted
is it possible just to remove pod with a name starting with "plank%" to avoid to restart all pods running in this workspace ? 
I'm using squashctl :
```
$ squashctl --version
squashctl version 0.5.7, created 2019-04-03.16:43:21
```

**Comment by mitchdraft** [comment]
Thanks for pointing the out @dwojciec 
I will add a filter

I had assumed that only squash-related pods would exist in the chosen squash namespace but there is no need for that constraint
