### ISSUE TITLE
Support process selection in vscode extension

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/squash#196]

**Comment by tenitski** [comment]
How does it currently work? Will it debug the entrypoint process only?

**Comment by mitchdraft** [comment]
yes, this is supported in VSCode
specify your process with the `Process Match` field in the squash extension settings
It will try to do a regex match, passing the value to this `squashctl` flag:

```
      --process-match string       optional, if passed, Squash will try to find a process in the target container that matches (regex, case-insensitive) this string. Otherwise Squash chooses the first process.
```

just forgot to close the issue

**Comment by tenitski** [comment]
Perfect! Thanks for letting know!
