### ISSUE TITLE
Running dep ensure -v hangs

### ISSUE THREAD

**Issue by agbrowne** [solo-io/squash#214]
***********************************
UPDATED 
***********************************

Following the instructions in the BUILDING.md file, when I run 'dep ensure -v' it hangs.

It appears to download everything then get as far as shown below, then just hangs. 

_(106/110) Wrote github.com/GoogleContainerTools/skaffold@v0.7.0
(107/110) Wrote k8s.io/apiextensions-apiserver@master
(108/110) Wrote github.com/hashicorp/consul@v1.4.0
(109/110) Wrote github.com/hashicorp/vault@v1.0.1
(110/110) Wrote k8s.io/kubernetes@v1.10.2_

Attaching strace to the dep process reveals that it is doing nothing but waiting for something:-

_strace -p 3443
strace: Process 3443 attached
futex(0xb689b0, FUTEX_WAIT, 0, NULL_

The disk usage on the /home filesystem seems to be steadily increasing, although I don't know which process is causing this:-

_Every 1.0s: df |grep -E "/home|/tmp"                                     <fqdn>: Tue May 21 14:56:57 2019

/dev/mapper/sys_vg-tmp_lv       5232640  414948   4817692   8% /tmp
/dev/mapper/data_vg-home_lv   103758336 5992612  97765724   6% /home

Every 1.0s: df |grep -E "/home|/tmp"                                     <fqdn>: Tue May 21 14:57:22 2019

/dev/mapper/sys_vg-tmp_lv       5232640  414948   4817692   8% /tmp
/dev/mapper/data_vg-home_lv   103758336 6000292  97758044   6% /home_

I'm running minikube on the server in question, within a VirtualBox VM.

The server is an ubuntu 18.04 OS which is fully up to date.

All obvious things like disk space, memory and swap are all OK.

What am I missing?

*******************************
UPDATE
*******************************

After waiting for over 20 mins, the 'dep ensure -v ' process completed, however when running 'make build' as instructed in the BUILDING.md file, I get the following errors.

There is no mention in BUILDING.md about an "image tag" and I can't find anything in the documentation about it either.

Error: could not set image tag: must specify an image tag, none found for build env vars: 
Usage:
  build parse-env release [flags]

Flags:
  -h, --help   help for release

Global Flags:
      --debug   enable verbose debug output

exit status 1
Error: could not set image tag: must specify an image tag, none found for build env vars: 
Usage:
  build parse-env version [flags]

Flags:
  -h, --help   help for version

Global Flags:
      --debug   enable verbose debug output

exit status 1
Error: could not set image tag: must specify an image tag, none found for build env vars: 
Usage:
  build parse-env image-tag [flags]

Flags:
  -h, --help   help for image-tag

Global Flags:
      --debug   enable verbose debug output

exit status 1
Error: could not set image tag: must specify an image tag, none found for build env vars: 
Usage:
  build parse-env container-prefix [flags]

Flags:
  -h, --help   help for container-prefix

Global Flags:
      --debug   enable verbose debug output

exit status 1
go run buildcmd/main.go validate-operating-parameters \
	 \
	 \
	 \
	
Error: could not set image tag: must specify an image tag, none found for build env vars: 
Usage:
  build validate-operating-parameters [flags]

Flags:
  -h, --help   help for validate-operating-parameters

Global Flags:
      --debug   enable verbose debug output

exit status 1
Makefile:20: recipe for target 'validate-computed-values' failed
make: *** [validate-computed-values] Error 1

**Comment by mitchdraft** [comment]
We've updated the building docs, thanks for the heads up!
https://github.com/solo-io/squash/blob/master/BUILDING.md
