### ISSUE TITLE
update documentation with usage of gdb

### ISSUE THREAD

**Issue by naseemkullah** [solo-io/squash#219]
[Documentation actually states that gdb is not yet supported](https://squash.solo.io/debuggers/).

However this repo says it is, would it be possible to update docs and add instructions on gdb debugging?

Cheers!

**Comment by naseemkullah** [comment]
I suppose it is in the works as per https://github.com/solo-io/squash/blob/master/next_docs.md ?

**Comment by mitchdraft** [comment]
thanks for the reminder, I've updated the docs, let me know if you have any questions
https://squash.solo.io/debuggers/gdb/
