### ISSUE TITLE
Squash pod crashed all the time

### ISSUE THREAD

**Issue by jun10k** [solo-io/squash#221]
K8S Version:  v1.13.5
Squash: v0.5.15
Description: 
1. Execute "squashctl deploy suqash"
2. The squash pods keep crashing and then reset. Have scaled the replica but it doesn't help
3. the logs of squash container is as below:
```
level=info msg="Watching namespaces" list="[core default itsma-uu6rb kube-public kube-system squash-debugger]"
{"level":"info","ts":"2019-06 17T07:03:57.786Z","logger":"v1.event_loop","caller":"v1/api_event_loop.sk.go:51","msg":"event loop started"}
E0617 07:03:57.795463       1 reflector.go:205] github.com/solo-io/squash/vendor/github.com/solo-io/solo-kit/pkg/api/v1/clients/kube/controller/controller.go:71: Failed to list *v1.Resource: the server could not find the requested resource (get debugattachments.squash.solo.io)

panic: failed to start kube shared informer factory: timed out while waiting for informer caches to syn
```

**Comment by mitchdraft** [comment]
It looks like you're using secure mode. In this case, you need to first register the resource. 

You can do this with `squashctl utils register-resources`

I have updated the docs: https://squash.solo.io/secure_mode/user/#per-cluster-configuration

thank you!
