### ISSUE TITLE
Question: Squash protocol stack and DAP compatibility

### ISSUE THREAD

**Issue by PavelSosin** [solo-io/squash#225]
What is Squash communication protocol stack? Is it compatible or may be compatible with Debugger adapter protocol proposal [Microsoft DAP](https://github.com/microsoft/debug-adapter-protocol) ?

**Comment by mitchdraft** [comment]
squash is a tool for connecting your debugger interface to another debugger. You express your debug intentions through flags passed to `squashctl` (or a squash ide extension does this for you).
The VSCode squash extension uses the DAP to communicate your debug intentions.
Does that answer your question?
