### ISSUE TITLE
addDebugAttachmentNotFound

### ISSUE THREAD

**Issue by baodongli** [solo-io/squash#24]
I followed the install process and installed squash on my k8s cluster:

devuser@c2-master:~/go/src/squash-demo$ kubectl get pods -n squash
NAME                           READY     STATUS    RESTARTS   AGE
squash-client-mb7cv            1/1       Running   0          26m
squash-client-pdfks            1/1       Running   0          26m
squash-client-wjj8w            1/1       Running   0          26m
squash-server-8dd6b6bf-8fdr7   1/1       Running   0          27m

I then followed the instructions to try the microservice (just renamed as squash-demo), but got an error as below:

squash --url=http://localhost:8001/api/v2 debug-container docker.io/baodongli/squash-demo:0.1 squash-demo-rc-fs6kj dlv

Failed adding container - check parameter names match container on the platform. error: [POST /debugattachment][404] addDebugAttachmentNotFound

**Comment by yuval-k** [comment]
the localhost:8001is coming form `kubectl proxy`? if so, this is a proxy to kubernetes APIs, to get to the squash API, you need to use the following url, (assuming you are using the latest release of squash, 0.2.1) 

http://localhost:8001/api/v1/namespaces/squash/services/squash-server:http-squash-api/proxy/api/v2

Please see item number 3 [here](https://github.com/solo-io/squash/blob/master/docs/install/README.md).

**Comment by baodongli** [comment]
Yes, I ran kubectl proxy
The list command works, but the debug-container always return the error

devuser@c2-master:~/go/src/squash-demo$ squash --url=http://localhost:8001/api/v1/namespaces/squash/services/squash-server:http-squash-api/proxy/api/v2 list attachments
State |ID |Debugger |Image |Debugger Address
devuser@c2-master:~/go/src/squash-demo$ squash --url=http://localhost:8001/api/v1/namespaces/squash/services/squash-server:http-squash-api/proxy/api/v2 debug-container docker.io/baodongli/squash-demo:0.1 squash-demo-rc-fs6kj dlv
**Failed adding container - check parameter names match container on the platform. error: [POST /debugattachment][400] addDebugAttachmentBadRequest**

**Comment by yuval-k** [comment]
The most probably cause for this is a mismatch between the image in the command line and the image in the pod spec. These two are checked to be an exact match to make sure the right container is debugged.
Can you confirm that the image in the pod spec is exactly 'docker.io/baodongli/squash-demo:0.1' ?

**Comment by baodongli** [comment]
devuser@c2-master:~/go/src/squash-demo$ kubectl describe pod squash-demo-rc-fs6kj
Name:           squash-demo-rc-fs6kj
Namespace:      default
Node:           c2-minion2/10.86.7.104
Start Time:     Tue, 09 Jan 2018 17:13:00 -0500
Labels:         app=squash-demo
Annotations:    <none>
Status:         Running
IP:             10.244.2.52
Controlled By:  ReplicationController/squash-demo-rc
Containers:
  squash-demo:
    Container ID:   docker://1dbde5bf996fef6c9affacf922e1d42280ee943d12fe800efb93f0c133e5917f
    Image:          docker.io/baodongli/squash-demo:0.1
    Image ID:       docker-pullable://baodongli/squash-demo@sha256:e654631d4774154ea4ae082ff8235da8762f6ef2e32b03162d1da0f64b07dbf2
    Port:           8080/TCP
    State:          Running
      Started:      Tue, 09 Jan 2018 17:13:07 -0500
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wxmfc (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  default-token-wxmfc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-wxmfc
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
devuser@c2-master:~/go/src/squash-demo$ squash --url=http://localhost:8001/api/v1/namespaces/squash/services/squash-server:http-squash-api/proxy/api/v2 debug-container docker.io/baodongli/squash-demo:0.1 squash-demo-rc-fs6kj dlv
Failed adding container - check parameter names match container on the platform. error: [POST /debugattachment][400] addDebugAttachmentBadRequest

**Comment by baodongli** [comment]
yes, see output from 'kubectl describe pod'. Thanks for your quick response.

**Comment by yuval-k** [comment]
no problem!
can you please provide the squash logs?
use this commands to get them:
server logs:
```
kubectl logs -nsquash -l app=squash-server
```
client logs:
```
kubectl logs -nsquash -l app=squash-client
```
Please place the output in between  three backticks ( \```  ), as it will format much nicer :)

**Comment by baodongli** [comment]
kubectl logs -nsquash -l app=squash-server

```time="2018-01-10T15:13:37Z" level=info msg="DebugattachmentAddDebugAttachmentHandler called!" 
time="2018-01-10T15:13:37Z" level=info msg="Trying to locate" podname=squash-demo-rc-fs6kj 
time="2018-01-10T15:13:37Z" level=info msg="Located node for pod" node=c2-minion2 podname=squash-demo-rc-fs6kj 
time="2018-01-10T15:13:37Z" level=info msg="GetDebugAttachmentsHandler called!" 
time="2018-01-10T15:13:59Z" level=debug msg="GetDebugAttachmentsHandler timing out!" 
time="2018-01-10T15:14:00Z" level=info msg="GetDebugAttachmentsHandler called!" 
```

kubectl logs -nsquash -l app=squash-client

```time="2018-01-10T15:14:00Z" level=debug msg="watchForAttached - calling PopContainerToDebug" params="&{<nil> [] 0xc42033e130 0xc42033e140 [] 0xc420018042 30000000000 <nil> <nil>}" 
time="2018-01-10T15:14:30Z" level=warning msg="watchForAttached - error calling function:" err="context deadline exceeded" 
time="2018-01-10T15:14:31Z" level=debug msg="watchForAttached - calling PopContainerToDebug" params="&{<nil> [] 0xc4204283f0 0xc420428400 [] 0xc4203fa080 30000000000 <nil> <nil>}" 
time="2018-01-10T15:15:01Z" level=warning msg="watchForAttached - error calling function:" err="context deadline exceeded" 
time="2018-01-10T15:15:02Z" level=debug msg="watchForAttached - calling PopContainerToDebug" params="&{<nil> [] 0xc42033e000 0xc42033e030 [] 0xc4203a6000 30000000000 <nil> <nil>}" 
time="2018-01-10T15:15:32Z" level=warning msg="watchForAttached - error calling function:" err="context deadline exceeded" 
time="2018-01-10T15:15:33Z" level=debug msg="watchForAttached - calling PopContainerToDebug" params="&{<nil> [] 0xc42000e720 0xc42000e8d0 [] 0xc420018030 30000000000 <nil> <nil>}" 
time="2018-01-10T15:16:03Z" level=warning msg="watchForAttached - error calling function:" err="context deadline exceeded" 
time="2018-01-10T15:16:04Z" level=debug msg="watchForAttached - calling PopContainerToDebug" params="&{<nil> [] 0xc42000ee10 0xc42000ee30 [] 0xc420018068 30000000000 <nil> <nil>}" 
time="2018-01-10T15:16:34Z" level=warning msg="watchForAttached - error calling function:" err="context deadline exceeded" 
time="2018-01-10T15:16:35Z" level=debug msg="watchForAttached - calling PopContainerToDebug" params="&{<nil> [] 0xc420428010 0xc420428020 [] 0xc4203fa000 30000000000 <nil> <nil>}" 
time="2018-01-10T15:17:05Z" level=warning msg="watchForAttached - error calling function:" err="context deadline exceeded" 
time="2018-01-10T15:17:06Z" level=debug msg="watchForAttached - calling PopContainerToDebug" params="&{<nil> [] 0xc42033e000 0xc42033e030 [] 0xc4203a6000 30000000000 <nil> <nil>}" 
```

**Comment by yuval-k** [comment]
I think i see the issue, the command line should also contain the container name. Please try this command:
```
 squash --url=http://localhost:8001/api/v1/namespaces/squash/services/squash-server:http-squash-api/proxy/api/v2 debug-container docker.io/baodongli/squash-demo:0.1 squash-demo-rc-fs6kj squash-demo dlv
```

**Comment by baodongli** [comment]
That works! Thanks!

**Comment by yuval-k** [comment]
Great! can I close this issue?
BTW we really love feedback about squash, and hear more about how people use it and the value the get from it. If you have any insights feel free post them in an issue, or reach out on slack (slack.solo.io)

**Comment by baodongli** [comment]
Absolutely. 
The detailed instructions are very helpful. somehow I missed the container name when copying/ issuing the command.
