### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by computerquip-work** [solo-io/squash#262]
Per the title.

**Comment by yuval-k** [comment]
We are not currently actively developing squash right now. Hoping to invest in it in the future to add more functionality. Pull requests are welcome!

**Comment by computerquip-work** [comment]
Appreciate the update! I'm unsure if the issue should be left open or not so I'll leave it open.

**Comment by Sodman** [comment]
Let's close it for now, if folks are wondering they can search the issues! Thanks!
