### ISSUE TITLE
Add Support for Windows

### ISSUE THREAD

**Issue by synax** [solo-io/squash#29]
Hi, I'm really excited about squash and on my mac, it works very well. 

Are there any plans to also add windows support for: 

-  squash-cli: So debugging on Windows would work in vs code.
-  squash-client: So pods running on windows nodes in a k8s cluster could be debugged.

The most important component I would like to see on windows is the squash-cli. This because I have to use Windows at work. So I would like to be able to debug in vs-code on windows natively. Right now I have to use an ubuntu VM, which is a bit painful :). The only thing missing as far as I see for my windows setup is the squash cli bin. I've tried to compile it on windows without success. 

I used these commands on my windows machine using powershell core 6.0 and a working go environment:

- $ mkdir -p $GOPATH/src/github.com/solo-io
- $ cd $GOPATH/src/github.com/solo-io
- $ git clone https://github.com/solo-io/squash
- $ cd squash
- $ dep ensure
- $ go build -o squash ./cmd/squash-cli

I get the following exception:

github.com/solo-io/squash/pkg/utils/processwatcher
pkg\utils\processwatcher\watcher.go:18:11: undefined: syscall.Stat_t
pkg\utils\processwatcher\watcher.go:19:12: undefined: syscall.Stat

These structs do not exist in the windows package of syscall. So in order to make it work on windows we would have to add a windows specific implementation for these OS dependent calls.

Cheers,

Stefan

**Comment by yuval-k** [comment]
I made the squash cli not depend on them, so it should now compile on windows.

**Comment by ilevine** [comment]
Thanks for your feedback and I am very happy you tried squash.

The cli should complicate now. 
I am adding this ticket to the roadmap and we will defiantly add window support soon.

**Comment by synax** [comment]
Hey, cool! Thanks for the quick response. I can confirm that the cli compiles now and it works!

**Comment by cimpoesub** [comment]
Hi. Any update on when this will go live?
