### ISSUE TITLE
dockerfile for istio images in examples

### ISSUE THREAD

**Issue by christian-posta** [solo-io/squash#44]
Is this dockerfile for this image handy somewhere?

https://github.com/solo-io/squash/blob/master/contrib/istio-example/istio.yaml#L264

**Comment by yuval-k** [comment]
This was built using the regular istio Dockerfiles, the only difference that we used a patched version pilot, to add the squash filter to envoy.
Recently pilot added support for webhooks, and we are planning to integrate squash to istio that way, so vanilla istio can be used.

**Comment by christian-posta** [comment]
thanks @yuval-k
